---
title: "Untitled"
author: "Gerard Castell i Joan Valls"
date: "Friday, March 20, 2015"
output: pdf_document
---

## Multivariate model

Despite the fact of not being the optimal choice, a multivariate linear model was fitted to the data. It seems reasonable to think that observations are not independent, since they are comming from the same cow. However, this model can also lead to some interesting results. 

From the bivariate linear regressions models fitted in the previous section, both time and dose seem to have some kind of effect in the PCV. Following this rationale, the first multivariant model used to explain differences in PCV among observations, was the one with the additive effects of the variables time and dose. Since both were significant, two F-tests were performed right after, to test if the models adding the new additive effect of number of births or the second order interaction between time and dose, were significantly different with respect to the first one. The variable with the lowest p-value under 0.05 was added to the model. This procedure was followed until no other covariates or interactions below 3rd order could be added, because they would not produce a significantly better model. Note that with this procedure the most parsimonious model was ensured to be found. Table \ref{taulamodels} summarizes the results of all models considered. Finally, the best model explaining the data was, 

$$
PCV= 15.82 + 2.43X_{time} -0.32X_{doseM} -1.31X_{doseH} -0.34X_{nbirth} + 0.48X_{doseM}X_{time} + 2.35X_{doseH}X_{time}
$$



```{r, echo=FALSE, results='hide'}
cows <- read.table("data/cattle_mes dades.txt", header = TRUE, 
                   sep = "\t", dec = ",", na.strings = "")

names(cows) <- c("id", "dose", "pcv", "time", "nbirth")

cows$id <- as.factor(cows$id)
cows$dose <- factor(cows$dose, levels=c("L", "M", "H"))

# dep variable:
# pcv: the higher the better.

# indep variables:
# dose: we want to know if the dose is associated with lower PCV
# nbirth: we want to know if this covariate influences the effect of the dose.
# time: we dont particularly want to see differences in time, but maybe 
# 3rd observations of the doses are higher, ...

# we do not want:
# id: we dont want the effect of the dose to be explained by the cow.

# Each observation of each cow will be considered independent.
taula <- matrix(ncol=6, nrow=33)
model <- lm(pcv ~ time + dose, data=cows)
summary(model)
model0 <- model
colnames(taula) <- c("Formula", "Variables", colnames(summary(model)$coef))
as.character(model$terms)->formu
taula[1,1] <- paste(formu[c(2,1,3)], collapse="")
taula[1:4,-(1:2)] <-  round(summary(model)$coef,4)
taula[1:4,2] <- rownames(summary(model)$coef)

model <- lm(pcv ~ time + dose + nbirth, data=cows)
summary(model)
model1 <- model
as.character(model$terms)->formu
taula[6,1] <- paste(formu[c(2,1,3)], collapse="")
taula[6:10,-(1:2)] <-  round(summary(model)$coef,4)
taula[6:10,2] <- rownames(summary(model)$coef)
# dose H has a huge effect, in a possitive way. Also, in general higher
# times give better PCV values (which is logical). nbirth has a significative
# negative effect on the PCV.

model <- lm(pcv ~ time*dose + nbirth, data=cows)
summary(model)
model2 <- model
as.character(model$terms)->formu
taula[12,1] <- paste(formu[c(2,1,3)], collapse="")
taula[12:18,-(1:2)] <-  round(summary(model)$coef,4)
taula[12:18,2] <- rownames(summary(model)$coef)
# time and dose almost interact for high doses. This interaction is synergistic.
# higher times and dose H give even higher pcv, but this effect is higher when 
# combined together.

model <- lm(pcv ~ dose + time*nbirth, data=cows)
summary(model)
as.character(model$terms)->formu
taula[20,1] <- paste(formu[c(2,1,3)], collapse="")
taula[20:25,-(1:2)] <-  round(summary(model)$coef,4)
taula[20:25,2] <- rownames(summary(model)$coef)
model <- lm(pcv ~ time + dose*nbirth, data=cows)
summary(model)
as.character(model$terms)->formu
taula[27,1] <- paste(formu[c(2,1,3)], collapse="")
taula[27:33,-(1:2)] <- round(summary(model)$coef,4)
taula[27:33,2] <- rownames(summary(model)$coef)
# no other interactions are significative.
# print(xtable(taula, digits=c(0,0,0,2,2,2,2)), include.rownames=F)
# so... model selection, for the more pasimonious model says...
add1(model0, scope=~.^2+nbirth, test="F")
add1(model1, scope=~.^2, test="F")
add1(model2, scope=~.^2, test="F")

## final model:
model2 <- lm(pcv ~ time*dose + nbirth, data=cows, y=T, model=T)
summary(model2)

## diagnostic:

# high pcv has high positive errors. Doesnt seem to be random.
plot(model2$residuals, model2$y)
# problems with doseH
plot(model2$model$dose, model2$residuals)
# NO homoscedasticity
plot(model2$model$time, model2$residuals)
# not centered
plot(model2$model$nbirth, model2$residuals)

## BAD MODEL: we already know that, since obervations are not independent.
```

\begin{table}[ht]
\centering
\begin{tabular}{llllll}

\hline
Formula & Variables & Estimate & Std. Error & t value & Pr($>$$|$t$|$) \\ 
  \hline
pcv\~{}time + dose & (Intercept) & 12.3248 & 0.834 & 14.7788 & 0 \\ 
   & time & 3.5488 & 0.3686 & 9.6281 & 0 \\ 
   & doseM & 0.5629 & 0.7477 & 0.7528 & 0.454 \\ 
   & doseH & 3.2009 & 0.7163 & 4.4688 & 0 \\ 
   &  &  &  &  &  \\ 
  pcv\~{}time + dose + nbirth & (Intercept) & 13.9405 & 1.0288 & 13.5508 & 0 \\ 
   & time & 3.5807 & 0.3558 & 10.0628 & 0 \\ 
   & doseM & 0.4042 & 0.7241 & 0.5582 & 0.5785 \\ 
   & doseH & 3.0766 & 0.6928 & 4.4407 & 0 \\ 
   & nbirth & -0.3534 & 0.1402 & -2.5203 & 0.014 \\ 
   &  &  &  &  &  \\ 
  pcv\~{}time * dose + nbirth & (Intercept) & 15.8457 & 1.3496 & 11.7408 & 0 \\ 
   & time & 2.4286 & 0.6613 & 3.6725 & 5e-04 \\ 
   & doseM & -0.3189 & 1.748 & -0.1824 & 0.8558 \\ 
   & doseH & -1.3061 & 1.6714 & -0.7814 & 0.4372 \\ 
   & nbirth & -0.3355 & 0.1337 & -2.5092 & 0.0145 \\ 
   & time:doseM & 0.4806 & 0.8975 & 0.5355 & 0.594 \\ 
   & time:doseH & 2.3514 & 0.84 & 2.7993 & 0.0066 \\ 
   &  &  &  &  &  \\ 
  pcv\~{}dose + time * nbirth & (Intercept) & 13.7005 & 1.7826 & 7.6857 & 0 \\ 
   & doseM & 0.3971 & 0.7304 & 0.5436 & 0.5884 \\ 
   & doseH & 3.0706 & 0.6986 & 4.3956 & 0 \\ 
   & time & 3.7107 & 0.8637 & 4.2961 & 1e-04 \\ 
   & nbirth & -0.2983 & 0.362 & -0.8238 & 0.4128 \\ 
   & time:nbirth & -0.0292 & 0.1763 & -0.1655 & 0.869 \\ 
   &  &  &  &  &  \\ 
  pcv\~{}time + dose * nbirth & (Intercept) & 13.1703 & 1.5061 & 8.7446 & 0 \\ 
   & time & 3.5643 & 0.358 & 9.9571 & 0 \\ 
   & doseM & 0.6816 & 1.8149 & 0.3756 & 0.7084 \\ 
   & doseH & 4.8865 & 1.8079 & 2.7029 & 0.0086 \\ 
   & nbirth & -0.1845 & 0.2808 & -0.6572 & 0.5132 \\ 
   & doseM:nbirth & -0.0469 & 0.3645 & -0.1288 & 0.8979 \\ 
   & doseH:nbirth & -0.3978 & 0.3615 & -1.1004 & 0.275 \\ 
   \hline
\end{tabular}
\caption{All multivariant models considered for fitting the data, using a forward stepwise for selecting the model.}
\label{taulamodels}

\end{table}